apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-test-app
  labels:
    app: test-app
    component: db
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-test-app
  template:
    metadata:
      labels:
        app: sql-test-app
        version: v1
    spec:
      containers:
      - name: sql-test-app
        image: postgres:14.6-alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: configmap-db
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-db
                key: PG_PASSWORD
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
