apiVersion: v1
kind: Service
metadata:
  name: core-service
  labels:
    app: test-app
    component: api
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: core-service
    version: v1.0
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
